#!/bin/bash
make ccpic
echo RUNNING ccpic
./ccpic
mv xpartnew xpart
mv uqcijnew uqcij
echo RUNNING ccpic --restart -s3
./ccpic --restart -s3
mv xpartnew xpart
mv uqcijnew uqcij
echo RUNNING ccpic -s8
./ccpic -s8
