#!/bin/bash
make coptic
rm xpartnew
rm uqcijnew
rm xpart
rm uqcij
echo RUNNING coptic
./coptic -s5
echo RUNNING coptic --restart -s3
./coptic --restart -s3 -ck6
mv xpartnew xpart
mv uqcijnew uqcij
echo RUNNING coptic -s8 -ck6
./coptic -s8 -ck6
echo If the last ====== Finished uqcijckeck and ====== Finished xpartcheck
echo show no warnings or diagnostics. Everything is OK for restarting.
